version: '3.8'

networks:
  monitoring:
    driver: bridge

services:

  django:
    build: ./project
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - prometheus
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    restart: 'no'
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    restart: 'no'
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3001:3000
    depends_on:
      - prometheus
    networks:
      - monitoring

volumes:
    prometheus_data: {}
    grafana_data: {}